name: home_services_app
description: "A Home Services Flutter Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.0
  flutter_svg: ^2.2.1
  lottie: ^2.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # General Images
    - assets/images/

    # Hero Images
    - assets/images/categories/

    # Service Images
    - assets/images/services/cleaning/
    - assets/images/services/maintenance/
    - assets/images/services/finishing/
    - assets/images/services/moving/
    - assets/images/services/security/
    - assets/images/services/outdoor/
    - assets/images/services/daily_services/

    # Icons
    - assets/icons/

    # ✅ Fonts
    - assets/fonts/

  # ✅ Fonts
  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/APP_Font.ttf
          weight: 400